// The 58 official wilayas of Algeria with home-delivery shipping rates (DZD)
const WILAYAS = [
  { code: 1,  name: "أدرار",            shipping: 1400 },
  { code: 2,  name: "الشلف",            shipping: 600 },
  { code: 3,  name: "الأغواط",          shipping: 700 },
  { code: 4,  name: "أم البواقي",       shipping: 700 },
  { code: 5,  name: "باتنة",            shipping: 700 },
  { code: 6,  name: "بجاية",            shipping: 600 },
  { code: 7,  name: "بسكرة",            shipping: 900 },
  { code: 8,  name: "بشار",             shipping: 1100 },
  { code: 9,  name: "البليدة",          shipping: 450 },
  { code: 10, name: "البويرة",          shipping: 450 },
  { code: 11, name: "تمنراست",          shipping: 1600 },
  { code: 12, name: "تبسة",             shipping: 700 },
  { code: 13, name: "تلمسان",           shipping: 600 },
  { code: 14, name: "تيارت",            shipping: 600 },
  { code: 15, name: "تيزي وزو",         shipping: 600 },
  { code: 16, name: "الجزائر",          shipping: 400 },
  { code: 17, name: "الجلفة",           shipping: 700 },
  { code: 18, name: "جيجل",             shipping: 600 },
  { code: 19, name: "سطيف",             shipping: 600 },
  { code: 20, name: "سعيدة",            shipping: 600 },
  { code: 21, name: "سكيكدة",           shipping: 600 },
  { code: 22, name: "سيدي بلعباس",      shipping: 600 },
  { code: 23, name: "عنابة",            shipping: 600 },
  { code: 24, name: "قالمة",            shipping: 600 },
  { code: 25, name: "قسنطينة",          shipping: 600 },
  { code: 26, name: "المدية",           shipping: 450 },
  { code: 27, name: "مستغانم",          shipping: 600 },
  { code: 28, name: "المسيلة",          shipping: 700 },
  { code: 29, name: "معسكر",            shipping: 600 },
  { code: 30, name: "ورقلة",            shipping: 900 },
  { code: 31, name: "وهران",            shipping: 600 },
  { code: 32, name: "البيض",            shipping: 700 },
  { code: 33, name: "إليزي",            shipping: 1600 },
  { code: 34, name: "برج بوعريريج",     shipping: 600 },
  { code: 35, name: "بومرداس",          shipping: 450 },
  { code: 36, name: "الطارف",           shipping: 600 },
  { code: 37, name: "تندوف",            shipping: 1600 },
  { code: 38, name: "تيسمسيلت",         shipping: 600 },
  { code: 39, name: "الوادي",           shipping: 900 },
  { code: 40, name: "خنشلة",            shipping: 700 },
  { code: 41, name: "سوق أهراس",        shipping: 600 },
  { code: 42, name: "تيبازة",           shipping: 450 },
  { code: 43, name: "ميلة",             shipping: 600 },
  { code: 44, name: "عين الدفلى",       shipping: 600 },
  { code: 45, name: "النعامة",          shipping: 700 },
  { code: 46, name: "عين تموشنت",       shipping: 600 },
  { code: 47, name: "غرداية",           shipping: 900 },
  { code: 48, name: "غليزان",           shipping: 600 },
  { code: 49, name: "تيميمون",          shipping: 1400 },
  { code: 50, name: "برج باجي مختار",   shipping: 1600 },
  { code: 51, name: "أولاد جلال",       shipping: 900 },
  { code: 52, name: "بني عباس",         shipping: 1400 },
  { code: 53, name: "عين صالح",         shipping: 1600 },
  { code: 54, name: "عين قزام",         shipping: 1600 },
  { code: 55, name: "تقرت",             shipping: 900 },
  { code: 56, name: "جانت",             shipping: 1600 },
  { code: 57, name: "المغير",           shipping: 900 },
  { code: 58, name: "المنيعة",          shipping: 1100 }
];

module.exports = { WILAYAS };
